spring:
  #    数据库源
  datasource:
    #云上测试数据库连接
#    url: jdbc:mysql://localhost:3306/smart_community?useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: smart_community
#    password: iRxaCp6cTHkstC3S
#    driver-class-name: com.mysql.jdbc.Driver
    #云上纯净数据库
    url: jdbc:mysql://localhost:3306/smart_community2?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: smart_community2
    password: rbEP3mfdDRLAFede
    driver-class-name: com.mysql.jdbc.Driver
    #本地数据库
#    url: jdbc:mysql://localhost:3306/smart_community?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver