#资源路径【注意一定要'/'结尾,前置路径除外】
prop:
  #文件上传前置路径 src/main/resources/static 有文件服务器用这个，没有则注释
  #    upload: classpath:/static
  #综合平台-员工管理：上传员工个人简历
  upload-business-sys-user-resume: /pdf/business/sysUser/resume/

  #基础档案-房屋审核管理：审核信息相关照片
  upload-estate-examine: /img/estateExamine/

  #管家服务-咨询建议：新增咨询建议照片上传路径
  upload-advice: /img/advice/
  #管家服务-投票管理：新增投票标题照片上传路径
  upload-vote-title: /img/vote/title/
  #管家服务-投票管理：新增投票候选人照片上传路径
  upload-vote-candidate: /img/vote/candidate/
  #管家服务-社区话题：新增话题照片上传路径
  upload-gambit: /img/gambit/
  #管家服务-社区主题明细：新增主题照片上传路径
  upload-gambit-theme: /img/gambitTheme/
  #管家服务-物品管理：新增物品信息照片上传路径
  upload-article: /img/article/
  #管家服务-物品管理：新增物品信息详情照片上传路径
  upload-article-detail: /img/articleDetail/
  #管家服务-报事报修：新增报事报修照片上传路径
  upload-repair: /img/repair/
  #管家服务-业委会管理：业委会成员照片上传路径
  upload-owners-committee: /img/ownersCommittee/
  #管家服务-装修管理：装修须知doc,docx文件上传路径
  upload-decoration-notice-doc: /doc/decorationNotice/
  #管家服务-装修管理：营业执照照片上传路径
  upload-decoration-business-license: /img/decoration/businessLicense/
  #管家服务-装修管理：资质证书照片上传路径
  upload-decoration-qualification-certificate: /img/decoration/qualificationCertificate/
  #管家服务-装修管理：装修图纸照片上传路径
  upload-decoration-decoration-drawings: /img/decoration/decorationDrawings/
  #管家服务-装修管理：装修申请表上传路径
  upload-decoration-decoration-application-form: /img/decoration/decorationApplicationForm/
  #管家服务-装修管理：装修承诺书上传路径
  upload-decoration-decoration-commitment: /img/decoration/decorationCommitment/
  #管家服务-问卷调查：封面照片
  upload-questionnaire-cover-photo: /img/questionnaire/coverPhone/
  #管家服务-设施/设备检查：检查照片
  upload-facilities-check-photo: /img/facilities/checkPhone/
  #管家服务-设施/设备管理：设施/设备doc,docx文件上传路径
  upload-facilities-doc: /doc/facilitiesDoc/
  #管家服务-租赁合同管理：租赁合同模版上传路径
  upload-lease-contract-pdf: /pdf/leaseContract/
  #管家服务-租赁合同管理：租赁合同预览上传路径
  upload-lease-contract-preview-pdf: /pdf/leaseContractPreview/
  #管家服务-租赁合同管理：租赁合同签名照片（签名区照片）
  upload-lease-contract-signature-photo: /img/leaseContractSignature/
  #管家服务-租赁合同管理：租赁签署合同上传路径（已签署的合同）
  upload-lease-contract-signed-pdf: /pdf/leaseContractSigned/
  #管家服务-租赁合同管理：租赁有效（正式）合同上传路径（盖章后的合同）
  upload-lease-contract-valid-pdf: /pdf/leaseContractValid/
  #管家服务-新版家政服务管理：处理完成照片上传路径
  upload-housekeeping-service-handler-phone: /img/housekeepingService/handlerPhone/
  #管家服务-安全管理：安全管理文件上传路径
  upload-security-management-file-img: /img/securityManagement/


  #运营管理-公告管理：新增公告信息照片上传路径
  upload-announcement: /img/announcement/
  #运营管理-公告管理：新增公告信息doc,docx文件上传路径
  upload-announcement-doc: /doc/announcement/
  #运营管理-主办方管理：新增主办方信息 营业执照照片上传路径
  upload-sponsor: /img/sponsor/
  #运营管理-活动管理：新增活动信息 照片上传路径
  upload-activity: /img/activity/
  #运营管理-资讯管理：新增资讯信息 照片上传路径
  upload-news: /img/news/
  #运营管理-电子商务管理：新增电子商务信息 照片上传路径
  upload-electronic-commerce: /img/electronicCommerce/
  #运营管理-社区介绍管理：新增社区介绍信息 照片上传路径
  upload-community-introduction: /img/communityIntroduction/
  #运营管理-规程管理：规程doc,docx文件上传路径
  upload-regulation-management-doc: /img/regulationManagement/
  #运营管理：物资出入库记录发票照片上传路径
  upload-material-record-invoice: /img/meterialRecordInvoice/
  #运营管理：绿化任务检查照片上传路径
  upload-green-task-check-situation: /img/greenTaskCheckSituation/
  #运营管理：卫生任务检查照片上传路径
  upload-hygiene-task-check-situation: /img/hygieneTaskCheckSituation/
  #运营管理：户型说明照片上传路径
  upload-house-type-description: /img/houseTypeDesctiption/
  #运营管理：地理信息照片上传路径
  upload-geography: /img/geography/



  #系统管理-合同管理：合同doc,docx文件上传路径
  upload-contract-doc: /doc/contract/


  #收费管理-固定金额分摊：固定金额分摊缴纳凭证，照片上传路径
  upload-voucher: /img/voucher/

  #商场中心-商品照片：新增商品照片
  upload-shopping-goods: /img/shopping/goods/
  #商场中心-分类照片：新增分类照片
  upload-shopping-category: /img/shopping/category/
  #商品中心-供应商照片：新增供应商照片
  upload-shopping-supplier: /img/shopping/supplier/

  #管家服务-设施分类：设施分类照片上传路径
  upload-facilities-category: /img/facilitiesCategory/

  #App-个人资料：头像照片上传路径
  upload-app-head-sculpture: /img/headSculpture/
  #App-个人租赁信息：身份证正面上传路径
  upload-app-id-card-front: /img/idCard/Front/
  #App-个人租赁信息：身份证背面上传路径
  upload-app-id-card-back: /img/idCard/back/
  #App-租赁合同终止：腾空单上传路径
  upload-app-clearing-single: /img/clearingSingle/
  #App-访客邀请信息：身份证正面上传路径
  upload-app-visit-id-card-front: /img/visit/idCard/Front/
  #App-访客邀请信息：身份证背面上传路径
  upload-app-visit-id-card-back: /img/visit/idCard/back/
  #App-家政服务：家政服务提交照片上传路径
  upload-app-housekeeping-service-submit-phone: /img/housekeepingService/submitPhone/
  #App-家政服务：评价照片上传路径
  upload-app-housekeeping-service-evaluation-phone: /img/housekeepingService/evaluationPhone/


  #ButlerApp-个人资料：头像照片上传路径
  upload-butler-app-head-sculpture: /img/butlerAppHeadSculpture/
  #ButlerApp-巡检管理：巡更人员自拍人脸
  upload-butler-app-inspection-face: /img/inspectionFace/
  #ButlerApp-巡检管理：巡更人员拍摄现场
  upload-butler-app-inspection-space: /img/inspectionSpace/
  #ButlerApp-报事报修管理：工程维修图片信息
  upload-butler-app-engineering-repair: /img/engineeringRepair/
  #ButlerApp-报事报修工程维修管理：工作汇报图片信息
  upload-butler-app-work—report: /img/workReport/
  #ButlerApp-报事报修工程维修管理：完成维修图片信息
  upload-butler-app-complete-maintenance: /img/completeMaintenance/
  #ButlerApp-报事报修工程维修管理：验收照片图片信息
  upload-butler-app-acceptance: /img/acceptance/

  #Excel报表模版：上传Excel模版路径
  upload-model-excel: /excel-model/





  #H5页面-访客邀请自拍照上传
  upload-h5-visit: /img/h5/visit/

