#logging debug
logging:
  level:
    root: info
    com:
      api:
        dao: debug
  file:
    # 输出的log文件名
    name: intelligent-community
    # 输出的文件的路径
    path: /www/wwwroot/community.kadalai.com/apache-tomcat-8.5.61/webapps/logs
    # 限制日志文件的大小
    max-size: 100MB
    # 日志的保存天数
    max-history: 15
  config: classpath:logback-spring.xml