#支付宝支付
alipay:
  #支付宝分配给开发者的应用Id 2021002130681189
  aliPayAppId: "2021002131666192"

  #卖家支付宝用户号（对应异步通知返回参数seller_id）（可以不配置，只是异步通知时为了进一步校验而配置）
  #aliPaySellerId:
  #卖家支付宝账号（对应异步通知返回参数seller_email）（可以不配置，只是异步通知时为了进一步校验而配置）
  #alipayAccount:

  #商户应用公钥
  rsaPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAkXlBTSZS3PygMJuNczNE1KHE82QrTbEo/7ZdkbaEQu/C0G5u6W7hjZtoGIbBKqa/L5/e7GJGIKeyXWpLpF0OA7m+vN8pf17a7fEUpUVnTiF5QLjESHGdg3rc2/z2mAhjjYTOY01MFbv8ONZIDAMyhixdCz7Y5HguP+XZv3t1luRdk3iJ9NeuxlTAGI73usTF4QM7wUWn8uu701gOrgt6XjWF60l3f4skMUVw8gpqEhBHHAkXW+qDgmY72EqFhcGduUr7EcaLrekXf1cD1q4TbH10seio1oCWpykU8lD1/e3WwyTHFeRANW+14lHXIVSUTM7ZhmVEes/VIllXMMryrwIDAQAB"

  #商户应用私钥（注意，如果是Java语言，需要使用pkcs8格式的私钥，避免出现不可预知的错误）
  rsaPrivatKey: "MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCReUFNJlLc/KAwm41zM0TUocTzZCtNsSj/tl2RtoRC78LQbm7pbuGNm2gYhsEqpr8vn97sYkYgp7JdakukXQ4Dub683yl/Xtrt8RSlRWdOIXlAuMRIcZ2Detzb/PaYCGONhM5jTUwVu/w41kgMAzKGLF0LPtjkeC4/5dm/e3WW5F2TeIn0167GVMAYjve6xMXhAzvBRafy67vTWA6uC3peNYXrSXd/iyQxRXDyCmoSEEccCRdb6oOCZjvYSoWFwZ25SvsRxout6Rd/VwPWrhNsfXSx6KjWgJanKRTyUPX97dbDJMcV5EA1b7XiUdchVJRMztmGZUR6z9UiWVcwyvKvAgMBAAECggEANS/JAUUGvMccZkkpETpoavluQbKY5oHkRIHPegvqFXMFniESKgShMJ3mFDmIfGiUs/vWjERt8Vh+rQrE9yYSjqglpXZN/MSYdLBU5QwX9gflBhXHpdjsRvrvrvqwyesfQsmQj9vd+oBNehZWJxYwLcAgkJD8yaNq/W+zCgBAgNcTELKn3Q5CcIJ/hU+pzTJBn3PvWXU+egoOxCcgKGwkcGJlkiDhN4HoAMW36fqnArWks2q1dl+/uQWdtHffJsjW6K3izI3uBN+ugDNwrBw24yli4EQR5MK9t5wRBr+29fd5b1BjLHZ5vKCBk0svQU6qKOSB2D/fEY+I5dmuyyonuQKBgQDwtV6kv+JmTsFNEzfagmWuLa7ecudmDj0zV6meNEwkIbYUor4zjmuGDlrJcgCXrrrSL0oR5A/gJpiwnA3JKbhPRXk9kWfqsNJrPA1fd2Wy9WiNNBXGj61twLcuUcszBYUUZilKYgqyRn2KPZMU81ws8xe4d7ODxG6+x7dgboLtawKBgQCatxYIS9pKOMPmqrSpi7TNQd6xVPF2by8NqwCK9JbTEtT1PHdbfD/mPw+y/Rw4RxmBF9+LeiCjiu0xYbip9GFIMlxGYWkErvLjWdefnKcqYOuJCagq3aJA/SlWv0ja5THWyxgHlfhoY3wZYECd9JkTaShGmopmbYH6geEsppl8zQJ/OkuyoDPYoO5x4jjFTiZGeeiWcUliwVSxfb29VpNT3WxMrLK9Xb8gS1cupZr2icXHeR/60Fprfd3bHOqubAmumYQ52K9ee3hXfaENnBFOkAjfSVNT8sLZPbtuocktbS3pDQew+FLGRGbOAKzo8in+KOS22fYjg8YPDCVSRAh/rQKBgH5adjjyUeV59Kvm0EMDYPadDBVBbS4vYXtFI91YIfFiGN/rsQLbN4iACf9A7ZIcpvyiFaRgalWGOW6yA1Fxzx1aW7fzCASWKLF6hznIg1F98/5oD5pqhX+UAfXhpMt4kTp9hTN0zHncfdZvoHYf9ABBSm5W+h7q4lNHTTHdIc8lAoGAI/JVuTT3d8uDCpoksN/a+0Io8SZbUeepGy2G41FXQDH78DtMXZL96EX4esn5OL0UNJ8O0UoA6+B/JNQzMn4XI/0ZUjBkk132EHk4HZUVuRiPZElF9MW3EmS6ClGbLdrleKy4Tf/SlhZN3jg1v5wnmJr2++cn4zPpGOFb9HeU938="

  #支付宝公钥
  rsaAlipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArxvCSSnq0Fw6wCWF0ri+D3aT+PaxAy+2TU3LalN4EtIgywIhgse29nSBKlmi9po74dM+fChR4bu6L/mCA6B64ICl8NfZDu7g8imFP+6NXKnggzyP7kRtR8MkqwE/BAXWDdgDZ8ra8sZpOTY1jtSprI61qZtwq+X/t2+jVbptwqG9/ZQP9sjrWB9yASUDl3cA9IheyOKF5P3bE9j0+a+1aOp6l4X9teg+U2Rne8zuGe8ED788vsrUt8T2AS+WmTrT5ir5vwPtf85MhDFs8QjujlDVN1WEafmNVbcAlixb+nLP5nV7mbGo6rLzQYbnqi1wooxd2XzVlhykN30ku8PfOQIDAQAB"

  #服务器异步通知页面路径
  ##测试
  notifyUrl: "http://39.103.177.88:8804/IntelligentCommunity/alipay/getAlipayNotifyInfo"
  ##日常缴费
  dailyPaymentNotifyUrl: "http://39.103.177.88:8804/IntelligentCommunity/alipay/dailyPaymentNotifyInfo"
  ##报事报修
  reportRepairNotifyUrl: "http://39.103.177.88:8804/IntelligentCommunity/alipay/reportRepairNotifyInfo"

  #页面跳转同步通知页面路径
  returnUrl: "http://39.103.177.88:8804/IntelligentCommunity/alipay/return_url.do"

  #请求支付宝的网关地址
  aliPayGateway: "https://openapi.alipay.com/gateway.do"

  #加密方式
  signType: "RSA2"

  #仅支持JSON
  alipayFormat: "json"

  #请求使用的编码格式，如utf-8,gbk,gb2312等
  alipayCharset: "utf-8"

