#支付宝支付
alipay:
  #支付宝分配给开发者的应用Id 2021002148601736
  aliPayAppId: "2021002148601736"

  #卖家支付宝用户号（对应异步通知返回参数seller_id）（可以不配置，只是异步通知时为了进一步校验而配置）
  #aliPaySellerId:
  #卖家支付宝账号（对应异步通知返回参数seller_email）（可以不配置，只是异步通知时为了进一步校验而配置）
  #alipayAccount:

  #商户应用公钥
  rsaPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnS5sAnkgVJai2JR5Q2yOALJDz+t7j5mo7Yh+MVJoYdTaikNHj81sRKNJ33IXU97eMoaSfvl2nDAB9k1GemEYMLdfLmSMsacjhpls8NU86Srau5cPlOR2q2yvwNeuoI8sHAYZ8nTIxzdNQtWLxspqmZlalESj6+uQ5RERpTu9SoIh07N4DNTcqkQ72CvMe0Mx8TlSH9JGRIAL88+/cWUMsjTNxakCU2lPHFb0MvqqE2e9M7XIsnaK3jP/lgFN5iwpmAg3o76kmx4Hgj1xPPxax5AA60zZ0wSZoQ2DMXmtr0qS2owfdJ3xAlw9oJAXxFuhBMvxjjnIPf03TzGAmcIzjwIDAQAB"

  #商户应用私钥（注意，如果是Java语言，需要使用pkcs8格式的私钥，避免出现不可预知的错误）
  rsaPrivatKey: "MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCdLmwCeSBUlqLYlHlDbI4AskPP63uPmajtiH4xUmhh1NqKQ0ePzWxEo0nfchdT3t4yhpJ++XacMAH2TUZ6YRgwt18uZIyxpyOGmWzw1TzpKtq7lw+U5HarbK/A166gjywcBhnydMjHN01C1YvGymqZmVqURKPr65DlERGlO71KgiHTs3gM1NyqRDvYK8x7QzHxOVIf0kZEgAvzz79xZQyyNM3FqQJTaU8cVvQy+qoTZ70ztciydoreM/+WAU3mLCmYCDejvqSbHgeCPXE8/FrHkADrTNnTBJmhDYMxea2vSpLajB90nfECXD2gkBfEW6EEy/GOOcg9/TdPMYCZwjOPAgMBAAECggEBAIyhWCnuTarhC9pTHRviKDsfQ+Tnf6m/hZDgqmden93IH6/M+l4DIXdX0WSGI7D6mjsChFfuwtyDZ34DLaeY75fGuPY9KFRagkKPSxU+9Dx6BzIHuf0xW6uMlsMnNiqZbpG0M8rmCi2ToSDHB0RZHn9G4e/+adtO7FjGqM75YCckThacSPPvGBETqTccZyGJGNQKOxiF0jnNSdV8Do+QAu/saqExr0k80PP/TauGa61oVwS3I8UOrye5S8JNLXQUHCNlJhGCVBGZJ8CwKRh/uLVofo7V5fs6pkvsvwxACEvfz5u/riy0vIrza/5W0eA4XIywLUBrLH6acVMkRB2XvQECgYEA/mQHaHTLZilQvPJn2U/sIzcZekrptr9LDG9vAEg9fvFEGA/nNueYk/Detwe7o02mJ7/OzVAUg0j3gGo9BMRPeksTai2EklLYsmcGrkSuRC6R/Ygn2ou4FD7TlK1smrZX2el8SC4YcyaKrZROI83my8AklsRM+yHoUsomHlhK4K8CgYEAniz3zYKpReJUbTHY+9uVHPR5gV/c5n23nEs6gEaWR6wXamZLwWtO92p6PW+dt81wrDiEMBa8rsCPzP2oluAEZW5yKvxUI0ZYL/P5McGxS0xN0obfimOjw0x0Ca9Y+AbC7TZcYDTaXBFcxS6hnjhjsqaNSlXcDK/qj58ytxqF0yECgYAy1XpFfVFH0Om5WBc4bagaQWBt95pMUl2E1p+vxr/DJiMdS9BAQHdU2MUoffsY3uNc/g8tJ9txgJs0pgYbdb8MCQSQKxhaxQNYYw4KtN698TBrIVIVceYO5Z8SDrWtFNLpUKbtJYjtOb5sgT48GWENRhAJsKBRbq0mHg8P8UTFMQKBgCrwbCjnAorNITwvXwcoGfetSlrbqj0L/c85AN2Xy+4TApxIvuH3/ozd4+dPqJIf/ClUglYHphsOfTsZ1S14DNl4PRf8Pd8BlqkV4x0lxrp5MVsocADCgc9frtR+PHnAZCQ/MJ6RWoHJ2NRSj19DUZVK72oxmrX6/4MTpZHdalzhAoGBANSaKEsC4X8g6rS6XOHQ9ZNEPqGM4JyTMHAhBjh3tPmkIbqYvKwR3TQH1HAcr5UvtZl5dkLnni3JIV2ziFYJaRrkKNnTx/6hVXfhbD0Tpd6jGgUsp8MNqSv3R7ZNM2eqdaLWtefCOasEPvzaqNlnTyJ6aEdHbFWEZN3EXszypWzt"

  #支付宝公钥
  rsaAlipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArxvCSSnq0Fw6wCWF0ri+D3aT+PaxAy+2TU3LalN4EtIgywIhgse29nSBKlmi9po74dM+fChR4bu6L/mCA6B64ICl8NfZDu7g8imFP+6NXKnggzyP7kRtR8MkqwE/BAXWDdgDZ8ra8sZpOTY1jtSprI61qZtwq+X/t2+jVbptwqG9/ZQP9sjrWB9yASUDl3cA9IheyOKF5P3bE9j0+a+1aOp6l4X9teg+U2Rne8zuGe8ED788vsrUt8T2AS+WmTrT5ir5vwPtf85MhDFs8QjujlDVN1WEafmNVbcAlixb+nLP5nV7mbGo6rLzQYbnqi1wooxd2XzVlhykN30ku8PfOQIDAQAB"

  #服务器异步通知页面路径
  ##测试
  notifyUrl: "http://test.kaidalai.cn/api/app/user/alipay/getAlipayNotifyInfo"
  ##日常缴费
  dailyPaymentNotifyUrl: "http://test.kaidalai.cn/api/app/user/alipay/dailyPaymentNotifyInfo"
  ##报事报修
  reportRepairNotifyUrl: "http://test.kaidalai.cn/api/app/user/alipay/reportRepairNotifyInfo"
  ##商城购物
  shoppingNotifyUrl: "http://test.kaidalai.cn/api/app/user/alipay/shoppingNotifyInfo"
  ##房屋租赁
  leaseNotifyUrl: "http://test.kaidalai.cn/api/app/user/alipay/leaseNotifyInfo"

  #页面跳转同步通知页面路径
  returnUrl: "https://test.kaidalai.cn/api/app/user/alipay/return_url.do"

  #请求支付宝的网关地址
  aliPayGateway: "https://openapi.alipay.com/gateway.do"

  #加密方式
  signType: "RSA2"

  #仅支持JSON
  alipayFormat: "json"

  #请求使用的编码格式，如utf-8,gbk,gb2312等
  alipayCharset: "utf-8"

