#极光推送
jg:
  #极光app密钥
  appKey: 00e20fef79ee804d5c9abb54
  #极光主密钥
  masterSecret: 236de00049f87c76d28d63be
  #管家app密钥
  butlerAppKey: 028adb7b9eda661fefdf3072
  #管家app主密钥
  butlerMasterSecret: d8b9c1cbc6812e81453151f3


aliyun:
  sms:
    #产品名称:云通信短信API产品,开发者无需替换
    product: "Dysmsapi"
    #产品域名,开发者无需替换
    domain: "dysmsapi.aliyuncs.com"
    #此处需要替换成开发者自己的AK(在阿里云访问控制台寻找)
    accessKeyId: "LTAI4GD3BFj2WBDSiywy9sZG"
    accessKeySecret: "dNdS9urtnmMfewe8QlGWKECXkEVLVf"