#资源配置文件
res:
  #访客邀请分享有效时长
  visitShareTime: 3
  #新版访客邀请门禁访客照片转发http 地址
  visitorsUrl: http://192.168.31.130:9001/manage/test2/test2
  #信息服务系统照片存放地址
  communityLocation: http://39.103.177.88:8804/static

#立林对讲机系统（人才公寓对接）
lilin:
  #API版本号。当前为1.0。
  version: 1.0
  #签名算法版本。当前为1.0。
  signatureVersion: 1.0
  #小区号
  neighNo: 450108500003
  #第三方唯一标示
  clientId: 83b4ee0b0c0abb7969f51ec614744c96
  #第三方密钥
  clientSecret: 72126e68b501d89ca0b490fe95628efe
  #立林对讲机系统测试服务器地址
  serviceLocation: http://rd.iot.leelen.com/
  #API接口
  api:
    #添加设备人脸识别api方法
    faceMethod: addFaceRecognize