#支付宝支付
alipay:
  #支付宝分配给开发者的应用Id
  aliPayAppId: "2016100100638656"

  #卖家支付宝用户号（对应异步通知返回参数seller_id）（可以不配置，只是异步通知时为了进一步校验而配置）
  #aliPaySellerId:
  #卖家支付宝账号（对应异步通知返回参数seller_email）（可以不配置，只是异步通知时为了进一步校验而配置）
  #alipayAccount:

  #商户应用公钥
  rsaPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgm9K47O8f5XwIuHX3poN3LHHYC/uh0Bgt9RBQYrjwtGH4WSksb3KDOGIPZ0iFza9ubPru4w3dlaOGiqF6Cs3qsJ+SOR3GxYy397//owafxqlKm0iK3DXnd04F36Hlxm6/8xy0Qo6TUUC4h0+5+NfpMPLgziA5UeUeqR9U3iWjNGhhhdExHbxvrWOpZnwBa9zFDPYiXXDRAqtKYOZQtjHLnCDD9eF/lbAwATpDucV+6D/t/38t+DwT1cVLNuQBEpUd2jRgZnxLZDChyUUwejqzdueGhoHgmR3raNRqLiiBRsMjWlWosTxN+1xMCBeFTL54ufE48y+kUuM7TmvvPfmxwIDAQAB"

  #商户应用私钥（注意，如果是Java语言，需要使用pkcs8格式的私钥，避免出现不可预知的错误）
  rsaPrivatKey: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCCb0rjs7x/lfAi4dfemg3cscdgL+6HQGC31EFBiuPC0YfhZKSxvcoM4Yg9nSIXNr25s+u7jDd2Vo4aKoXoKzeqwn5I5HcbFjLf3v/+jBp/GqUqbSIrcNed3TgXfoeXGbr/zHLRCjpNRQLiHT7n41+kw8uDOIDlR5R6pH1TeJaM0aGGF0TEdvG+tY6lmfAFr3MUM9iJdcNECq0pg5lC2McucIMP14X+VsDABOkO5xX7oP+3/fy34PBPVxUs25AESlR3aNGBmfEtkMKHJRTB6OrN254aGgeCZHeto1GouKIFGwyNaVaixPE37XEwIF4VMvni58TjzL6RS4ztOa+89+bHAgMBAAECggEARE2havIBQNK0qJ+ZmpETt0FFhcIz55G31CwLbBYeRTPSMx6v+//F4c7suE8jvgJFggyM4m5/0LFswpkH/Fc9VGd7GBLDqGSMiZ1Ocu7NJUg/u6LgpNz3nExvBiaVPHQV78QRUBRKCZKc+umTunzf5fk+Bl49aVN9lmey1VYtiFmzDzy36C+5JmP/fkaRt2l6oyF5SI3dD32zF8ktACkk8ugPj+yXwaKD4XGng0twGo5qwZUZU8aK/1IQZ/FaMEV7Isaea1AN0wpcbs4TOOj86b0udVTGqS1Dini8OU3sXIcOYwvWflirfFcIJQnaT2XjwI4L7yQbyczcjX8h7hNQWQKBgQC6cX7JrZwmBl5/M2sJ+U5l6DcKWVSuafbz9tdEBo0eHbt4CQQYudDredRFU70O8MxL7NKO0Ok9gVj4Ei6z/afZXy0hS8Y5ardftS4Z5Dpnzl2OdB/z4MQIE99WAOZaOLsP3WI4K63uaGZDpLfQYmYShHl1fP77f7EL5cdgxJERpQKBgQCzGKAYh1K7vbttgeCaxJpiXIKf2Y++sV9sviAHvK+jZU3xX7JB1Gm+mQuYrTclSlJU5RPKgwyu+p81n48pm1NsPbQkQ7aDXYx9oMvAm6JmH+cl5V9tjhk2rgQN5qiTyqYRqanKRPBfVliHz3+A6T7JI9TG0W+YQJm7qjp6nSYS+wKBgD0/NXBZONeA9iABKyOOo4N0okgjCl91beu85gBxyn/fMot/IrpgqFICponTtWKoFeTHOnAyDrzmtexgRLlaFX6h9nhepRKNjQnCwg89WzZoo3E9kpWR+7PPm2lsSD/RLRpMFozvRGbyIs4L2Vp6SJ/CpwfCdRz3WJjY9gNC74kFAoGAZejhUJPQNBxmho2c7PRqlQXnHmaCMRRlJE+bkkt/9g4zJ+I4YNUpxtb3jk0iUAnWh5BCjr27feYGqlC8+gP0mGcUFn6hYGbfBq10w4jMBCirMxkuD/0Hw+GJVQ+nZVGu5eYRQ5Ou49ESV1VvTD9tBq9o6ClMwuofkHXxCMxbWfkCgYEAn9/kF9omOMPJXn21UxkcGaOMD4fFLWlMtYqMOX613NsTQNZVn9GbVBiTW9d9VwB9UDx/jtE8wG3mU9GM5J71fbJd5RmRf82g2c8Zyl6KpfzcwMiw0DbQrY3771f9qRSHKECbAmqe9VJSyZ3oYrKRz9r0Qh7ikHfreVw0fT2sVaY="

  #支付宝公钥
  rsaAlipayPublicKey: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAn/+kAfDzQ+y7jkY3ngiKl0W2HD40BlLSW18IQDxWJyStOkDXZQe4uJH9y2tmLkIrICMrexy1ekXtRGVG4vX2AmEQB6x9/SOHZGdUCn9BxsHWM+5afJbeZJCcQUkN9rC5u2tu2F81UQCnaFUIz0r/Hecmk1TAfktQ8AxSDc4/wHi4Pg/xU1pVOln5XvZ+WKwHu904f+TibweUOUyp4ahxfUPAahJ5QmVpZrEqV45rouyyMc+9seeL4PFLjAk/a9dxetKYdCzDX4JA/Jji0TX1CacAYllCEpgTddpbOf4HxCFnw8sl8BHe6DfZKrv7l2V3AaQtSvfTFkz6wDJM81mToQIDAQAB"

  #服务器异步通知页面路径
  notifyUrl: "http://test.akuhotel.com:8804/IntelligentCommunity/alipay/getAlipayNotifyInfo"

  #页面跳转同步通知页面路径
  returnUrl: "http://test.akuhotel.com:8804/IntelligentCommunity/alipay/return_url.do"

  #请求支付宝的网关地址
  aliPayGateway: "https://openapi.alipay.com/gateway.do"

  #加密方式
  signType: "RSA2"

  #仅支持JSON
  alipayFormat: "json"

  #请求使用的编码格式，如utf-8,gbk,gb2312等
  alipayCharset: "utf-8"

