spring:
  #    数据库源
  datasource:
    #测试数据库连接
    url: jdbc:mysql://localhost:3306/smart_community?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: smart_community
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver