server:
    port: 9001
    servlet:
        context-path: /
spring:
#    文件上传
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
#   静态资源路径
#    resources: classpath:/static/
    resources: classpath:/static/

    #springboot 自带的jackson配置
    jackson:
        #配置springboot时区
        time-zone: GMT+8
        #配置时间格式 格式化日期 格式化时间
        date-format: yyyy-MM-dd HH:mm:ss
    task:
      scheduling:
        pool:
            size: 30
    profiles:
        #开发环境
        include: dev
        #生产环境
#        include: pro
        #测试环境
#        include: test

#mybatis
mybatis:
    mapper-locations: classpath:mapper/*/*/*.xml
    #下划线自动转换成实体
    configuration:
        map-underscore-to-camel-case: true


