server:
    port: 9001
    servlet:
        context-path: /
spring:
#    文件上传
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
#   静态资源路径
#    resources: classpath:/static/
    resources: classpath:/static/

    #springboot 自带的jackson配置
    jackson:
        #配置springboot时区
        time-zone: GMT+8
        #配置时间格式 格式化日期 格式化时间
        date-format: yyyy-MM-dd HH:mm:ss
    task:
      scheduling:
        pool:
            size: 30
    profiles:
        #开发环境（本地开发）
        include: dev
        #测试环境（云上测试服务器）
#        include: test
        #生产环境(南宁本地)
#        include: pro
    #mq基本配置
    rabbitmq:
        addresses: 120.55.167.78
        port: 5672
        username: jcook40362136173633536
        password: d3tTyh
#        virtual-host: /
        connection-timeout: 15000
    #整合rabbitmq消费者
        listener:
            simple:
                concurrency: 1
                max-concurrency: 1
                #签收模式
                acknowledge-mode: manual
                #限流 - 每次只消费一条
                prefetch: 3
        cache:
            channel:
                #缓存中保持的Channel数量
                size: 25
#mybatis
mybatis-plus:
    mapper-locations: classpath:mapper/*/*/*.xml
    # 以下配置均有默认值,可以不设置
    global-config:
        db-config:
            #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
            id-type: auto
            #字段策略 IGNORED:"忽略判断"  NOT_NULL:"非 NULL 判断")  NOT_EMPTY:"非空判断"
            field-strategy: NOT_EMPTY
            #数据库类型
            db-type: MYSQL
    #下划线自动转换成实体
    configuration:
        map-underscore-to-camel-case: true
        # 如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
        call-setters-on-nulls: true

