server:
    port: 9001
    servlet:
        context-path: /

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/IntelligentCommunity?characterEncoding=utf8&useSSL=false
        username: root
        password: jlw15906763698
        driver-class-name: com.mysql.jdbc.Driver
#mybatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.aku.model

swagger:
    enable: true