server:
    port: 9001
    servlet:
        context-path: /
spring:
#    文件上传
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
#   静态资源路径
#    resources: classpath:/static/
    resources: classpath:/static/
    #    数据库源
    datasource:
        #本地数据库连接
        url: jdbc:mysql://localhost:3306/IntelligentCommunity?characterEncoding=utf8&useSSL=false
        username: root
        password: jlw15906763698
        #测试数据库连接
#        url: jdbc:mysql://localhost:3306/smart_community?characterEncoding=utf8&useSSL=false
#        username: smart_community
#        password: 123456
        driver-class-name: com.mysql.jdbc.Driver


#mybatis
mybatis:
    mapper-locations: classpath:mapper/*/*/*.xml
    #下划线自动转换成实体
    configuration:
        map-underscore-to-camel-case: true

#logging debug
logging:
    level:
        com:
            api:
                dao: debug

#资源路径【注意一定要'/'结尾,前置路径除外】
prop:
    #文件上传前置路径 src/main/resources/static 有文件服务器用这个，没有则注释
#    upload: classpath:/static

    #管家服务-咨询建议：新增咨询建议照片上传路径
    upload-advice: /img/advice/
    #管家服务-投票管理：新增投票标题照片上传路径
    upload-vote-title: /img/vote/title/
    #管家服务-投票管理：新增投票候选人照片上传路径
    upload-vote-candidate: /img/vote/candidate/
    #管家服务-社区话题：新增话题照片上传路径
    upload-gambit: /img/gambit/
    #管家服务-物品管理：新增物品信息照片上传路径
    upload-article: /img/article/

    #运营管理-公告管理：新增公告信息照片上传路径
    upload-announcement: /img/announcement/
    #运营管理-公告管理：新增公告信息doc,docx文件上传路径
    upload-announcement-doc: /doc/announcement/
    #运营管理-主办方管理：新增主办方信息 营业执照照片上传路径
    upload-sponsor: /img/sponsor/
    #运营管理-活动管理：新增活动信息 照片上传路径
    upload-activity: /img/activity/

    #收费管理-固定金额分摊：固定金额分摊缴纳凭证，照片上传路径
    upload-voucher: /img/voucher/

    #App-个人资料：头像照片上传路径
    upload-app-headSculpture: /img/headSculpture/



