server:
    port: 9001
    servlet:
        context-path: /
spring:
#    文件上传
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
#   静态资源路径
    resources: classpath:/static/
#    数据库源
    datasource:
        url: jdbc:mysql://localhost:3306/IntelligentCommunity?characterEncoding=utf8&useSSL=false
        username: root
        password: jlw15906763698
#        url: jdbc:mysql://localhost:3306/smart_community?characterEncoding=utf8&useSSL=false
#        username: smart_community
#        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
#redis数据库
#    redis:
#        # Redis数据库索引（默认为0）
#        database: 0
#        #Redis服务器地址
#        host: 127.0.0.1
#        # Redis服务器连接端口
#        port: 6379
#        # Redis服务器连接密码（默认为空）
#        password:
#        jedis:
#            pool:
#                # 连接池最大连接数（使用负值表示没有限制）
#                max-active: 20
#                # 连接池最大阻塞等待时间（使用负值表示没有限制）
#                max-wait: -1
#                # 连接池中的最大空闲连接
#                max-idle: 10
#                # 连接池中的最小空闲连接
#                min-idle: 0
#        # 连接超时时间（毫秒）
#        timeout: 1000
#    jmx:
#        enabled: true

#mybatis
mybatis:
    mapper-locations: classpath:mapper/*/*.xml
    #下划线自动转换成实体
    configuration:
        map-underscore-to-camel-case: true
    #别名
#    type-aliases-package: com.aku.model

#logging debug
logging:
    level:
        com:
            api:
                dao: debug

#资源路径【注意一定要'/'结尾,前置路径除外】
prop:
    #文件上传前置路径 src/main/resources/static
    upload: src/main/resources/static
    #管家服务-咨询建议：新增咨询建议照片上传路径
    upload-advice: /img/advice/
    #管家服务-投票管理：新增投票标题照片上传路径
    upload-vote-title: /img/vote/title/
    #管家服务-投票管理：新增投票候选人照片上传路径
    upload-vote-candidate: /img/vote/candidate/
    #管家服务-社区话题：新增话题照片上传路径
    upload-gambit: /img/gambit/
    #管家服务-物品管理：新增物品信息照片上传路径
    upload-article: /img/article/

    #运营管理-公告管理：新增公告信息照片上传路径
    upload-announcement: /img/announcement/
    #运营管理-公告管理：新增公告信息doc,docx文件上传路径
    upload-announcement-doc: /doc/announcement/
    #运营管理-主办方管理：新增主办方信息 营业执照照片上传路径
    upload-sponsor: /img/sponsor/
    #运营管理-活动管理：新增活动信息 照片上传路径
    upload-activity: /img/activity/



